# Training config
training:
  epochs: 30
  batch_size: 14
  loss_combine_sources: no
  loss_use_multidomain: no
  mix_coef: 10.0
  val_dur: 80.0
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  patience: 1000
  lr_decay_patience: 80
  lr_decay_gamma: 0.3
  weight_decay: 0.00001
# Data config. Change values of irs_1_dir and irs_2_dir to your local ones.

#where is the testdir?
data:
  toy_run: True
  backing_track_input: False
  concat_type: no_concat #concat_2 is the proper one. concat_1 was the attempt with low results
  target: bass #drum or bass or vocal
  root: /media/alia/2aa686b1-fdb5-4cc9-b12d-c1fcdc0782cc/datasets/leakage_removal/
  train_dir: /media/alia/2aa686b1-fdb5-4cc9-b12d-c1fcdc0782cc/datasets/leakage_removal/train
  irs_metadata: /home/alia/Documents/projects/leakage_removal/asteroid/egs/musdb18/X-UMX/local/irs.csv
  output: dummy_concat_x-umx_outputs_exp1_bass_no_concat
  irs_1: Aachen Impulse Response Dataset
  irs_1_dir: /media/data/alia/Documents/datasets/AIR_1_4
  irs_2: Room Impulse Response and Noise Database
  irs_2_dir: /media/data/alia/Documents/datasets/Room Impulse Response and Noise Database 
  sample_rate: 44100
  num_workers: 4
  seed: 42
  seq_dur: 6.0
  samples_per_track: 64
  source_augmentations:
    - gain
    - channelswap
  leakage_removal: True
  inputs:
    - clean_backing_track
    - degraded_audio_mix

# Should we train one target at a time, or train all the models together (i.e vocals + everything else, guitar + everything else, etc)
  outputs:
    - degraded_instrument_track
    - degraded_backing_track

# Network config
model:
  pretrained: null
  bidirectional: yes
  window_length: 4096
  in_chan: 4096
  nhop: 1024
  hidden_size: 512
  bandwidth: 16000
  nb_channels: 2
  spec_power: 1

